# -*- coding: utf-8 -*-
"""senai_python_aula6_VETORES_MATRIZES.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/124L3lolyeH7pZ6mLlw0AOH4l4oGv8X4w

# Rascunho das atividades de aula (26/03/2024)
"""

import numpy as np

def transp(mat):
    """
    mat = [[2, 3], [4, 5], [6, 7]]

    [[2, 3],
     [4, 5]
     [6, 7]]

     mat_transposta:
     [[2, 4, 6],
      [3, 5, 7]]
    """
    nl = len(mat)  # linhas na matriz mat
    nc = len(mat[0])  # colunas em mat
    tr = []
    for j in range(nc):
        linha = []
        for i in range(nl):
            linha.append(mat[i][j])
        tr.append(linha)
    return tr

mat = [[2, 3], [4, 5], [6, 7]]
transp(mat)

def mult_mat(A, B):
    if len(A[0]) != len(B):
        raise ValueError("Dimensoes incompativeis")

    nl = len(A)  # linhas do resultado
    nc = len(B[0])  # colunas do resultado

    resultado = [[ 0 for _ in range(nc)]
                     for _ in range(nl)]

    for i in range(nl):
        for j in range(nc):
            for k in range(len(B)):
                resultado[i][j] += A[i][k]*B[k][j]

    return resultado

A = [[1,2,3], [4,5,6]]  # 2x3
B = [[7,8,9], [10,11,12],[13,14,15]]  # 3x3
mult_mat(A, B)  # 2x3

B = [[7,8,9], [10,11,12],[13,14,15]]  # 3x3
I = [[1, 0, 0], [0, 1, 0], [0, 0, 1]]  # 3x3
mult_mat(I, B)

import math
PI = 3.1416  # 180 graus
math.cos(PI/4)

from math import pi
pi

import numpy as np
arr  = np.array([1,2.0,3])
arr.dtype

arr1 = np.array([1,2])
arr2 = np.array([3,4])
arr3 = np.vstack((arr1,arr2))
print(arr3)

arr3[0,0] = -1
print(arr3)
print(arr1)



print(arr1)
arr4 = arr1
arr4[0] = -1
print(arr4)

print(-1*arr4)

from math import cos, sin, pi
# Definindo os vértices do quadrado original
vertices = [[-1, 1], [-1, -1], [1, 1], [1, 1]]
print('vertices:'); print(vertices)
verticesT = transp(vertices)
print('verticesT:'); print (verticesT)

# Ângulo de rotação em radianos (45 graus)
angulo = (45) * pi / 180
# Matriz de rotação no sentido anti-horário
matriz_rotacao = [[cos(angulo), sin(angulo)],
                  [sin(angulo), cos(angulo)]]
# Multiplicação da matriz de rotação pela matriz de vértices
vertices_rotacionados = mult_mat(matriz_rotacao, verticesT)
print('vertices_rotacionados:'); print(vertices_rotacionados)

